version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5408:5432"
    environment:
      POSTGRES_DB: various_small_datasets
      POSTGRES_USER: various_small_datasets
      POSTGRES_PASSWORD: insecure
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
      - .:/host
  web:
    build: src/
    ports:
      - "8000:8000"
    links:
      - database
    environment:
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "various_small_datasets.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/vsd/static=/static"
      UWSGI_PY_AUTORELOAD: 1
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      SECRET_KEY: insecure
      DATABASE_NAME: various_small_datasets
      DATABASE_USER: various_small_datasets
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: insecure
    volumes:
      - ./src:/app
